version: "3.7"
services:
  php:
    build: ./docker-images/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/
    command: php -S 0.0.0.0:8000 -t public public/index.php
    ports:
      - "8000:8000"
    environment:
      APP_ENV: docker-local
      APP_DEBUG: 'true'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  redisdata:
    driver: local