version: "3.7"
services:
  php:
    build: ./docker-images/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    ports:
      - "9001:9000"
    environment:
      APP_ENV: docker-local
      APP_DEBUG: 'true'
    networks:
    - mailable_network

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
    networks:
      - mailable_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - mailable_network

networks:
  mailable_network:
    driver: bridge

volumes:
  redisdata:
    driver: local