version: "3.7"
services:
  php:
    build: ./docker-images/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/
    command: php -S 0.0.0.0:8000 -t public public/index.php
    ports:
      - "8000:8000"
    environment:
      APP_ENV: docker-local
      APP_DEBUG: 'true'
    depends_on:
      - redis
      - mysql

  php-queue:
    restart: always
    build: ./docker-images/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/
    command: php artisan queue:work
    depends_on:
      - redis
      - mysql

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  mysql:
      image: 'mysql:8.0'
      ports:
          - '3307:3306'
      env_file:
        - .env
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
          - 'mysqldata:/var/lib/mysql'
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local