<?php

use Laravel\Lumen\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    public \Faker\Generator $faker;

    protected function setUp(): void
    {
        $this->faker  = Faker\Factory::create();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }
}
